name: shiver_env
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - aiohttp
  - bottleneck
  - pyproj
  - h5netcdf
  - netcdf4
  - xarray
  - jupyterlab
  - dask
  - pandas
  - cartopy
  - jupyter-book[version='<1.0']
  - fsspec
  - matplotlib
  - rioxarray
  - python=3.11
  - numpy
  - zarr
  - s3fs
