title: "SHeffield Ice Velocity ExploreR (SHIVER) - Cloud access to a unified dataset of satellite-derived ice surface velocity measurements for the Antarctica Ice Sheet and Greenland Ice Sheet"
author: Benjamin Davison
logo: _static/SHIVER_logo_stacked_v1_black_on_transparent_background_simplified.png

# Top-level repository settings
repository:
  url: https://github.com/ben-davison/SHIVER-build-zarr
  path_to_book: docs
  branch: main

# HTML settings (adds sidebar buttons)
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

# Control execution of Jupyter notebooks when building
execute:
  execute_notebooks: "off"

# Enable substitutions
parse:
  myst_enable_extensions:
    - substitution
  myst_substitutions:
    antarcticaIcon: '![AntarcticaIcon](/_static/icons/antarcticaIcon.svg)'
    greenlandIcon: '![GreenlandIcon](/_static/icons/greenlandIcon.svg)'
    paletteIcon: '![PaletteIcon](/_static/icons/paletteIcon.svg)'
    uploadIcon: '![UploadIcon](/_static/icons/uploadIcon.svg)'
    advancedIcon: '![AdvancedIcon](/_static/icons/advancedIcon.svg)'
    layersIcon: '![LayersIcon](/_static/icons/layersIcon.svg)'
    trendIcon: '![TrendIcon](/_static/icons/trendIcon.svg)'
    graphIcon: '![GraphIcon](/_static/icons/graphIcon.svg)'
    excelIcon: '![ExcelIcon](/_static/icons/excelIcon.svg)'

# Sphinx settings
sphinx:
  extra_extensions:
    - sphinx_copybutton
  config:
    html_static_path: ["_static"]
    html_css_files: ["custom.css"]
